services:
  web:
    build: .
    container_name: senpick
    volumes:
      - .:/code
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80" # {host_port}:{port} host_port 를 수정해야 배포시 반영됨 
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - /etc/letsencrypt/live/senpick.kr:/etc/nginx/ssl:ro
    depends_on:
      - web
